Title: ICD Codes and Mappings
Version: 1
Last Updated: June 16, 2023
Contact: support@openmortality.org
Developer Contact: Richard Wen <rrwen.dev@gmail.com>
Abbreviation: icd
Tag: icd,wbd,cmea,wva,cghr

# Open Mortality Settings
Dataset Table: dp_dataset
Dataset Refresh View: mvdpdataset
Data Table: dp_data
Database User: omdevdbuser

Data:

# List of data consisting of the following keys:
# - Name: name of the ICD dataset
# - File: path to the raw data file used to create the ICD dataset
# - Description: description of the ICD dataset
# - Permission: set user group permissions for Open Mortality - defaulted to user if not set (optional)
# - Tag: comma separated tag words (optional)
# - Category: the group for the individual data in the dataset - currently main or supplementary, and defaults to main (optional)
# - Columns: list of column processing and description config, see tabbed below
#   - Name: raw dataset column name
#   - Rename: Renamed processed column name, the default is the raw dataset column name (optional)
#   - Description: data dictionary description for column
#   - Remove Leading Dashes: set to True to remove leading dashes and False (default) to skip this (optional)
#   - Type: data type for column (optional)

- Name: icd10
  File: data/icd_10to11_map_single.xlsx
  Description: "International Classification of Diseases Revision 10 (ICD-10) data from the World Health Organization (WHO)."
  Permission: user
  Tag: icd
  Category: main
  Columns:
  
  - Name: 10ClassKind
    Rename: kind
    Description: "ICD-10 entity kind. One of chapter, block, or category. Chapters are top level classification entities. Blocks are high level groupings that do not have a code. Categories are entities that have a code."
    Type: str
  
  - Name: 10DepthInKind
    Rename: kind_depth
    Description: "ICD-10 depth for kind. For example, a category with kind_depth=2 means it is category whose parent is also a category but grand parent is not."
    Type: Int64
  
  - Name: icd10Chapter
    Rename: chapter
    Description: "ICD-10 chapter for the entity."
    Type: str
  
  - Name: icd10Code
    Rename: code
    Description: "ICD-10 code for the entity."
    Type: str
  
  - Name: icd10Title
    Rename: title
    Description: "ICD-10 title of the entity."
    Type: str

- Name: icd11
  File: data/icd11.xlsx
  Description: "International Classification of Diseases Revision 11 (ICD-11) data from the World Health Organization (WHO)."
  Permission: user
  Tag: icd
  Category: main
  Columns:
  
  - Name: ClassKind
    Rename: kind
    Description: "ICD-11 entity kind. One of chapter, block, or category. Chapters are top level classification entities. Blocks are high level groupings that do not have a code. Categories are entities that have a code."
    Type: str
  
  - Name: DepthInKind
    Rename: kind_depth
    Description: "ICD-11 depth for kind. For example, a category with kind_depth=2 means it is category whose parent is also a category but grand parent is not."
    Type: Int64
  
  - Name: ChapterNo
    Rename: chapter
    Description: "ICD-11 chapter for the entity."
    Type: str
  
  - Name: Code
    Rename: code
    Description: "ICD-11 code for the entity. Note that the groupings do not have a code."
    Type: str
  
  - Name: Title
    Rename: title
    Description: "ICD-11 title of the entity."
    Remove Leading Dashes: True
    Type: str
  
  - Name: BlockId
    Rename: block_id
    Description: "ICD-11 identifier for high level groupings that do not bear a code"
    Type: str
  
  - Name: IsResidual
    Rename: is_residual
    Description: "True if the ICD-11 entity is a residual category (i.e. other specified or unspecified categories) and False if not."
    Type: bool
  
  - Name: isLeaf
    Rename: is_leaf
    Description: "True if the ICD-11 entity does not have any children and False if it does."
    Type: bool
  
  - Name: Primary tabulation
    Rename: is_primary_tabulation
    Description: "True if the ICD-11 entity is part of the primary tabulation and False if not."
    Type: bool
  
  - Name: Grouping1
    Rename: group1
    Description: "Grouping 1 that the ICD-11 entity is included in."
    Type: str
  
  - Name: Grouping2
    Rename: group2
    Description: "Grouping 2 that the ICD-11 entity is included in."
    Type: str
  
  - Name: Grouping3
    Rename: group3
    Description: "Grouping 3 that the ICD-11 entity is included in."
    Type: str
  
  - Name: Grouping4
    Rename: group4
    Description: "Grouping 4 that the ICD-11 entity is included in."
    Type: str
  
  - Name: Grouping5
    Rename: group5
    Description: "Grouping 5 that the ICD-11 entity is included in."
    Type: str
  
  - Name: BrowserLink
    Rename: browser_url
    Description: "Direct link to the ICD-11 entity in the web browser."
    Type: str
  
  - Name: Foundation URI
    Rename: foundation_url
    Description: "Link to unique ICD-11 entity identifier."
    Type: str
  
  - Name: Linearization (release) URI
    Rename: linear_url
    Description: "Link to unique identifier for this version of the classification. It includes the linearization name such as MMS and minor version identifier such as 2018 in it."
    Type: str

- Name: icd10_icd11
  File: data/icd_10to11_map_single.xlsx
  Description: "Mappings to convert from ICD-10 to ICD-11."
  Permission: user
  Tag: icd
  Category: supplementary
  Columns:
  
  - Name: 10ClassKind
    Rename: icd10_kind
    Description: "ICD-10 entity kind. One of chapter, block, or category. Chapters are top level classification entities. Blocks are high level groupings that do not have a code. Categories are entities that have a code."
    Type: str
  
  - Name: 10DepthInKind
    Rename: icd10_kind_depth
    Description: "ICD-10 depth for kind. For example, a category with kind_depth=2 means it is category whose parent is also a category but grand parent is not."
    Type: Int64
  
  - Name: icd10Chapter
    Rename: icd10_chapter
    Description: "ICD-10 chapter for the entity."
    Type: str
  
  - Name: icd10Code
    Rename: icd10_code
    Description: "ICD-10 code for the entity. Note that the groupings do not have a code."
    Type: str
  
  - Name: icd10Title
    Rename: icd10_title
    Description: "ICD-10 title of the entity."
    Remove Leading Dashes: True
    Type: str

  - Name: 11ClassKind
    Rename: icd11_kind
    Description: "ICD-11 entity kind. One of chapter, block, or category. Chapters are top level classification entities. Blocks are high level groupings that do not have a code. Categories are entities that have a code."
    Type: str
  
  - Name: 11DepthInKind
    Rename: icd11_kind_depth
    Description: "ICD-11 depth for kind. For example, a category with kind_depth=2 means it is category whose parent is also a category but grand parent is not."
    Type: Int64
  
  - Name: icd11Chapter
    Rename: icd11_chapter
    Description: "ICD-11 chapter for the entity."
    Type: str
  
  - Name: icd11Code
    Rename: icd11_code
    Description: "ICD-11 code for the entity. Note that the groupings do not have a code."
    Type: str
  
  - Name: icd11Title
    Rename: icd11_title
    Description: "ICD-11 title of the entity."
    Remove Leading Dashes: True
    Type: str
  
  - Name: ICD-11 FoundationURI
    Rename: icd11_foundation_url
    Description: "Link to unique ICD-11 entity identifier."
    Type: str
  
  - Name: Linearization (releaseURI)
    Rename: icd11_linear_url
    Description: "ICD-11 Link to unique identifier for this version of the classification. It includes the linearization name such as MMS and minor version identifier such as 2018 in it."
    Type: str

- Name: icd11_icd10
  File: data/icd_11to10_map_single.xlsx
  Description: "Mappings to convert from ICD-11 to ICD-10.\n\n**Note**: ICD-11 codes may map to multiple ICD-10 codes."
  Permission: user
  Tag: icd
  Category: supplementary
  Columns:
  
  - Name: icd11Chapter
    Rename: icd11_chapter
    Description: "ICD-11 chapter for the entity."
    Type: str
  
  - Name: icd11Code
    Rename: icd11_code
    Description: "ICD-11 code for the entity. Note that the groupings do not have a code."
    Type: str
  
  - Name: icd11Title
    Rename: icd11_title
    Description: "ICD-11 title of the entity."
    Remove Leading Dashes: True
    Type: str
    
  - Name: icd10Chapter
    Rename: icd10_chapter
    Description: "ICD-10 chapter for the entity."
    Type: str
  
  - Name: icd10Code
    Rename: icd10_code
    Description: "ICD-10 code for the entity. Note that the groupings do not have a code."
    Type: str
  
  - Name: icd10Title
    Rename: icd10_title
    Description: "ICD-10 title of the entity."
    Remove Leading Dashes: True
    Type: str

  - Name: Linearization (release) URI
    Rename: icd11_linear_url
    Description: "ICD-11 Link to unique identifier for this version of the classification. It includes the linearization name such as MMS and minor version identifier such as 2018 in it."
    Type: str
    
- Name: wbd10
  File: data/wbd10_raw.csv
  Description: "Wilson's Burden of Disease for ICD-10 (WBD-10) data from the Centre for Global Health Research (CGHR).\n\nGroups International Classification of Diseases (ICD) Revision 10 codes from the World Health Organization (WHO) into broader WBD-10 codes for three age groups (adult, child, and neonate)."
  Permission: user
  Tag: wbd
  Category: main
  Columns:
  
  - Name: age_group
    Rename: age
    Description: "Age group for the WBD-10 entity - adult (12-69 years old), child (1 month to 11 years old), and neo (under 1 month old)."
    Type: str
    
  - Name: kind
    Description: "WBD-10 entity kind. One of codex4, codex2, or codex. Codex4 are top level classification entities, codex2 are high level groupings, and codex are the WBD-10 codes at the lowest level."
    Type: str
    
  - Name: kind_depth
    Description: "WBD-10 depth for kind. For example, a codex with kind_depth=3 means means it has 2 higher levels above it. Codex4 has depth of 1 (highest) and Codex2 has depth of 2 (middle)."
    Type: Int64
  
  - Name: codex4
    Description: "WBD-10 codex4 - a higher level classification of the WBD-10 codes."
    Type: str
  
  - Name: codex2
    Description: "WBD-10 codex2 - a middle level classification that usually group several WBD-10 codes together."
    Type: str
  
  - Name: codex
    Rename: code
    Description: "WBD-10 codex or codes - the lowest level classification representing the WBD-10 codes themselves."
    Type: str
  
  - Name: codex4_title
    Description: "WBD-10 title for codex4."
    Type: str
  
  - Name: codex2_title
    Description: "WBD-10 title for codex2."
    Type: str
  
  - Name: codex_title
    Rename: title
    Description: "WBD-10 code/codex title."
    Type: str

  - Name: icd10_range
    Description: "Range of ICD-10 codes in the WBD-10 codex4/codex2 groupings or codex codes."
    Type: str
    
- Name: icd10_wbd10
  File: data/icd10towbd10_raw.csv
  Description: "Mappings to convert from ICD-10 to WBD-10."
  Permission: user
  Tag: icd,wbd
  Category: supplementary
  Columns:
  
  - Name: age_group
    Rename: wbd10_age
    Description: "Age group for the WBD-10 entity - adult (12-69 years old), child (1 month to 11 years old), and neo (under 1 month old)."
    Type: str
    
  - Name: kind
    Rename: wbd10_kind
    Description: "WBD-10 entity kind. One of codex4, codex2, or codex. Codex4 are top level classification entities, codex2 are high level groupings, and codex are the WBD-10 codes at the lowest level."
    Type: str
    
  - Name: kind_depth
    Rename: wbd10_kind_depth
    Description: "WBD-10 depth for kind. For example, a codex with kind_depth=3 means means it has 2 higher levels above it. Codex4 has depth of 1 (highest) and Codex2 has depth of 2 (middle)."
    Type: Int64
  
  - Name: codex4
    Rename: wbd10_codex4
    Description: "WBD-10 codex4 - a higher level classification of the WBD-10 codes."
    Type: str
  
  - Name: codex2
    Rename: wbd10_codex2
    Description: "WBD-10 codex2 - a middle level classification that usually group several WBD-10 codes together."
    Type: str
  
  - Name: codex
    Rename: wbd10_code
    Description: "WBD-10 codex or codes - the lowest level classification representing the WBD-10 codes themselves."
    Type: str
  
  - Name: codex4_title
    Rename: wbd10_codex4_title
    Description: "WBD-10 title for codex4."
    Type: str
  
  - Name: codex2_title
    Rename: wbd10_codex2_title
    Description: "WBD-10 title for codex2."
    Type: str
  
  - Name: codex_title
    Rename: wbd10_title
    Description: "WBD-10 code/codex title."
    Type: str

  - Name: icd10_range
    Description: "Range of ICD-10 codes in the WBD-10 codex4/codex2 groupings or codex codes."
    Type: str

  - Name: icd10
    Rename: icd10_code
    Description: "ICD-10 code for the entity."
    Type: str

- Name: cmea10
  File: data/cmea10_raw.csv
  Description: "Central Medical Evaluation Agreement for ICD-10 (CMEA-10) blocks from the Centre for Global Health Research (CGHR).\n\nThese blocks are used in the Central Medical Evaluation (CME) system to determine groups of ICD-10 codes considered to be in agreement for dual physician coding in Verbal Autopsies (VA)."
  Permission: user
  Tag: cmea
  Category: main
  Columns:

  - Name: icdequivalence_desc
    Rename: title
    Description: "CMEA-10 block title that represents a range of ICD-10 codes considered in agreement for assigning death codes in VAs."
    Type: str

  - Name: icdequivalence
    Rename: icd10_range
    Description: "Range of ICD-10 codes in the CMEA-10 block - each code is separated by a comma."
    Type: str

  - Name: icdequivalence_short
    Rename: icd10_range_short
    Description: "Range of ICD-10 codes in the CMEA-10 block - shortened to represent consecutive ranges with dashes for easier readability."
    Type: str

- Name: icd10_cmea10
  File: data/icd10tocmea10_raw.csv
  Description: "Mappings to convert from ICD-10 to CMEA-10."
  Permission: user
  Tag: icd,cmea
  Category: supplementary
  Columns:

  - Name: icdequivalence_desc
    Rename: cmea_title
    Description: "CMEA-10 block that groups ICD-10 codes considered in agreement for assigning death codes in VAs."
    Type: str

  - Name: icdequivalence
    Rename: icd10_range
    Description: "Range of ICD-10 codes in the CMEA-10 block - each code is separated by a comma."
    Type: str

  - Name: icd10_code
    Description: "ICD-10 code for the CMEA-10 block."
    Type: str

- Name: wva2016
  File: data/wva2016_raw.csv
  Description: "World Health Organization Verbal Autopsy 2016 (WVA-2016) codes that generalize ICD-10 codes for mortality."
  Permission: user
  Tag: wva
  Category: main
  Columns:

  - Name: kind
    Description: "WVA-2016 entity kind. One of group or code."
    Type: str

  - Name: kind_depth
    Description: "WVA-2016 depth for kind. For example, a category with kind_depth=2 means it is a code whose parent is a group."
    Type: str

  - Name: group
    Description: "WVA-2016 group containing a range of codes."
    Type: Int64

  - Name: group_title
    Description: "Title for WVA-2016 group."
    Type: str

  - Name: group_orig
    Description: "Original WVA-2016 group with leading text VAs-."
    Type: str

  - Name: code
    Description: "WVA-2016 code from the 2016 WHO VA instrument."
    Type: str

  - Name: code_orig
    Description: "Original WVA-2016 code with leading text VAs-."
    Type: str

  - Name: title
    Description: "Title for the WVA-2016 code."
    Type: str

  - Name: icd10_from_range_short
    Rename: icd10_range
    Description: "Range of ICD-10 codes that the WVA-2016 codes group together."
    Type: str

  - Name: icd10_to
    Rename: icd10_code
    Description: "ICD-10 codes that the WVA-2016 codes can be converted to."
    Type: str

- Name: icd10_wva2016
  File: data/icd10towva2016_raw.csv
  Description: "Mappings to convert from ICD-10 to WVA-2016."
  Permission: user
  Tag: icd,wva
  Category: supplementary
  Columns:

  - Name: wva2016_group
    Description: "WVA-2016 group containing a range of codes."
    Type: Int64

  - Name: wva2016_code
    Description: "WVA-2016 code from the 2016 WHO VA instrument."
    Type: str

  - Name: wva2016_group_title
    Description: "Title for WVA-2016 group."
    Type: str

  - Name: wva2016_title
    Description: "Title for the WVA-2016 code."
    Type: str

  - Name: icd10_range
    Description: "Range of ICD-10 codes that the WVA-2016 codes group together."
    Type: str

  - Name: icd10_code
    Description: "ICD-10 codes that the WVA-2016 codes can be converted to."
    Type: str

- Name: wva2022
  File: data/wva2022_raw.csv
  Description: "World Health Organization Verbal Autopsy 2022 (WVA-2022) codes that generalize ICD-10 codes for mortality."
  Permission: user
  Tag: wva
  Category: main
  Columns:

  - Name: who_va_code
    Rename: code
    Description: "WVA-2022 code from the 2022 WHO VA instrument."
    Type: str

  - Name: who_va_title
    Rename: title
    Description: "Title for the WVA-2022 code."
    Type: str

  - Name: icd_range_codes_short
    Rename: icd10_range
    Description: "Range of ICD-10 codes for the WVA-2022 codes."
    Type: str

- Name: icd10_wva2022
  File: data/icd10towva2022_raw.csv
  Description: "Mappings to convert from ICD-10 to WVA-2022."
  Permission: user
  Tag: icd,wva
  Category: supplementary
  Columns:

  - Name: who_va_code
    Rename: wva2022_code
    Description: "WVA-2022 code from the 2022 WHO VA instrument."
    Type: str

  - Name: who_va_title
    Rename: wva2022_title
    Description: "Title for the WVA-2022 code."
    Type: str

  - Name: icd_range_codes_short
    Rename: icd10_range
    Description: "Range of ICD-10 codes for the WVA-2022 codes."
    Type: str
  
  - Name: icd10_code
    Description: "ICD-10 code for the WVA-2022 code."
    Type: str

- Name: cghr10
  File: data/cghr10_raw.csv
  Description: "Centre for Global Health Research for ICD-10 (CGHR-10) codes for physician coded verbal autopsies."
  Permission: user
  Tag: cghr
  Category: main
  Columns:

  - Name: age
    Description: "CGHR-10 code age group. Age groups are divided into adult (12 to 69 years old), child (1 month to 11 years old), and neo (under 1 month old)."
    Type: str
  
  - Name: title
    Description: "CGHR-10 title for the code."
    Type: str

  - Name: icd10_range
    Description: "ICD-10 range for the CGHR-10 code."
    Type: str

- Name: icd10_cghr10
  File: data/icd10tocghr10_raw.csv
  Description: "Mappings to convert from ICD-10 to CGHR-10."
  Permission: user
  Tag: icd,cghr
  Category: supplementary
  Columns:

  - Name: cghr10_age
    Description: "CGHR-10 code age group. Age groups are divided into adult (12 to 69 years old), child (1 month to 11 years old), and neo (under 1 month old)."
    Type: str
  
  - Name: cghr10_title
    Description: "CGHR-10 title for the code."
    Type: str

  - Name: icd10_code
    Description: "ICD-10 code for the CGHR-10 code."
    Type: str

  - Name: icd10_range
    Description: "ICD-10 range for the CGHR-10 code."
    Type: str